config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]

    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :messages
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      if last_message.content?
        last_message.content
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
  # サイドバーのグループ部分に最新のメッセージが表示されるようにしている
  # show_last_messageメソッドでは、メッセージが投稿されている場合、されていない場合で処理を分ける
  # if (last_message = messages.last).present?」と記述することで、最新のメッセージを変数last_messageに代入しつつ、メッセージが投稿されているかどうかで場合分けする
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user

  validates :content, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :messages
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id]
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > ?", last_message_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
  end

  def new
    @group = Group.new
    # form_withで使用するための変数
    @group.users << current_user
    # 配列に要素を追加するためのもの
  end

  def create
    # new.html.hamlで指定された「name」キーに「グループ名」が、「user_ids」キーに「所属ユーザーのidの配列」の値が送信されている。
    @group = Group.new(group_params)
    # 保存がうまくいったかどうかで処理を分岐
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to root_path, notice: 'グループを更新しました'
      # Rails routesで確認・引数にIDを渡してあげる
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
    # 配列に対して保存を許可したい場合,キーの名称と関連づけてバリューに「[]」と記述
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    binding.pry
    params.require(:user).permit(:name, :email)
  end
end

  # params :keyword に値が入っていればそのまま処理は続けられ、
  # 空だった場合はそこで処理が終わります

  # 検索処理の内容は、whereメソッドを使用し、入力された値を含むかつ、
  # ログインしているユーザーのidは除外するという条件で取得しています

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_with model: group, local: true do |f|
  - if group.errors.any?
    .SettingGroupForm__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, "グループ名", class: 'SettingGroupForm__label'
    .SettingGroupForm__rightField
      = f.text_field :name, class: 'SettingGroupForm__input', placeholder: 'グループ名を入力してください'
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      %label.SettingGroupForm__label チャットメンバーを追加
    .SettingGroupForm__rightField
      .UserSearch
        %input#UserSearch__field.SettingGroupForm__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}/
      #UserSearchResult
  .SettingGroupForm__field
    .SettingGroupForm__leftField
      = f.label :name, value: "チャットメンバー", class: "SettingGroupForm__label"
    .SettingGroupForm__rightField
      .ChatMembers
        .ChatMember
          %p.ChatMember__name= current_user.name
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
        - group.users.each do |user|
          - if current_user.name != user.name
            .ChatMember
              %p.ChatMember__name 
                = user.name
              .ChatMember__remove.ChatMember__button{"data-user-id": user.id, "data-user-name": user.name} 削除
              %input{name: "group[user_ids][]", type:"hidden", value: user.id}
  .SettingGroupForm__field
    .SettingGroupForm__leftField
    .SettingGroupForm__rightField
      = f.submit class: 'SettingGroupForm__button'

  -# form_withメソッドは、引数の内容によってデータの送信先を推測しています。
    @groupに空のデータが入っている → 送信時にcreateアクションが呼ばれる
    @groupに既存のデータが入っている → 送信時にupdateアクションが呼ばれる
  -# errorsメソッド
    any?メソッドによって、エラーメッセージの有無を判定しています。
    full_messagesメソッドによってエラーメッセージ全件の内容を取得しています。

app/views/groups/edit.html.haml
.SettingGroupForm
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

-# = form_with model: @group, local: true do |f|
-#   = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
-#   = f.collection_check_boxes :user_ids, User.all, :id, :name
-#   = f.submit "Save", class: "SettingGroupForm__button"

app/views/groups/index.html.haml
.wrapper
  = render 'messages/side_bar'

app/views/groups/new.html.haml
.SettingGroupForm
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }



-# = form_with model: @group, local: true do |f|
-#   = f.text_field :name, class: "SettingGroupForm__input", placeholder: "グループ名を入力してください"
-#   = f.collection_check_boxes :user_ids, User.all, :id, :name
-#   -# 第２、第４引数は「フォームの表示」に使われます。
-#     第２引数で、表示されるためのデータを指定します。
-#     第４引数で、上記データのどのカラムを表示させるかを指定します。

-#   -# 第１、第３引数は、サブミットボタンが押された時に送信される「データの内容」を指定するものです。
-#     第１引数は、送信されるハッシュの「キー」の名称です。
-#     第３引数は、送信されるハッシュの「バリュー」です。
-#   = f.submit "Save", class: "SettingGroupForm__button"

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace3
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
    -# = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_main_chat.html.haml
.chat-main
  .chat-main__RightHeader
    .chat-main__RightHeader__Group
      .chat-main__RightHeader__Group__GroupName
        = @group.name
      .chat-main__RightHeader__Group__MemberList
        Member :
        - @group.users.each do |user|
          = user.name
    = link_to 'Edit', edit_group_path(@group), class: 'chat-main__RightHeader__EditButton'

  .chat-main__MessageField
    = render @messages
    -# render @messagesという記述で部分テンプレートを呼び出しています。
    -# これは、以下のコードを省略した書き方
    -# インスタンス変数の名前を単数形にしたものと、
    -# 部分テンプレートの名前が同じならこのような省略をすることができます
  .chat-main__Footer
    = form_with model: [@group, @message], html: {class: "chat-main__Footer__Form"}, local: true do |f|
      .chat-main__Footer__Form__Contents
        = f.text_field :content, class: 'chat-main__Footer__Form__Contents__InputContent', placeholder: 'type a message'
        = f.label :image, class: 'chat-main__Footer__Form__Contents__InputImage' do
          = icon('far', 'image', class: 'chat-main__Footer__Form__Contents__InputImage__FormIcon')
          = f.file_field :image, class: 'chat-main__Footer__Form__Contents__InputImage__Hidden'
      = f.submit 'Send', class: 'chat-main__Footer__Form__Submit'

app/views/messages/_message.html.haml
.chat-main__MessageField__MessageBox{data: {message: {id: message.id}}}
  .chat-main__MessageField__MessageBox__MessageInfo
    .chat-main__MessageField__MessageBox__MessageInfo__UserName
      = message.user.name
    .chat-main__MessageField__MessageBox__MessageInfo__Date
      = message.created_at.strftime("%Y年%m月%d日 %H時%M分")
      
  .chat-main__MessageField__MessageBox__Message
    - if message.content.present?
      .chat-main__MessageField__MessageBox__Message__Content
        = message.content
    = image_tag message.image.url, class: 'chat-main__MessageField__MessageBox__Message__Image' if message.image.present?

app/views/messages/_side_bar.html.haml
.chat-SideBar
  .chat-SideBar__LeftHeader
    .chat-SideBar__LeftHeader__List
      .chat-SideBar__LeftHeader__List__UserName
        = current_user.name
      .chat-SideBar__LeftHeader__List__IconList
        = link_to = link_to new_group_path,class:'chat-SideBar__LeftHeader__List__IconList__Pen' do
          = icon('fa', 'edit')
        = link_to edit_user_path(current_user),class:"chat-SideBar__LeftHeader__List__IconList__Sharin" do
          = icon('fa','cog')

  .chat-SideBar__GroupList
    - current_user.groups.each do |group|
      .chat-SideBar__GroupList__Group
        = link_to group_messages_path(group) do
          .chat-SideBar__GroupList__Group__Name
            = group.name
          .chat-SideBar__GroupList__Group__Message
            = group.show_last_message

app/views/messages/index.html.haml
= javascript_include_tag 'autoReload'
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/users/edit.html.haml
.AccountPage
  .AccountPage__title
    %h2 Edit Account
    %h5 アカウントの編集
    = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'Button'
    = link_to "トップページに戻る", :back, class: 'Button'
  .AccountPage__form
    = form_for(current_user) do |f|
      .FormField
        .FormField__label--normal
          = f.label :name
        .FormField__input--normal
          = f.text_field :name, autofocus: true
      .FormField
        .FormField__label--normal
          = f.label :email
        .FormField__input--normal
          = f.email_field :email
      = f.submit "Update", class: 'Button UserButton'